name: university_trello_analog
description: A new Flutter project.
version: 1.0.0+1
publish_to: none
environment:
  sdk: '>=2.19.2 <3.0.0'
dependencies:
  appflowy_board: 
    path: packages/appflowy_board
  bloc_test: ^9.1.1
  cross_scroll: ^0.0.75
  equatable: ^2.0.5
  firebase_auth: ^4.4.2
  firebase_core: ^2.10.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true